# Упражнение 1: Основные операции с тензорами
Цель: Понять и выполнять базовые операции с тензорами в PyTorch.
Инструкции:
Создайте случайный тензор формы (3, 4) и выведите его.            
Выполните следующие операции:               
Измените форму тензора на (4, 3).                           
Вычислите среднее значение и стандартное отклонение тензора.             
Выполните матричное умножение с другим тензором формы (4, 2).                          



In [1]:
import torch

tensor = torch.rand(3, 4)
print(tensor)



C:\Users\asus\anaconda3\Lib\site-packages\torch\_subclasses\functional_tensor.py:295: UserWarning: Failed to initialize NumPy: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.11 from "C:\Users\asus\anaconda3\python.exe"
  * The NumPy version is: "1.24.3"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed while importing _multiarray_umath: Не найден указанный модуль.
 (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\utils\tensor_numpy.cpp:84.)
  cpu = _conv

tensor([[0.5807, 0.9997, 0.0947, 0.3705],
        [0.7449, 0.7494, 0.0971, 0.2236],
        [0.5086, 0.9460, 0.9088, 0.6443]])


In [2]:
reshape= tensor.view(4, 3)
print(reshape)


tensor([[0.5807, 0.9997, 0.0947],
        [0.3705, 0.7449, 0.7494],
        [0.0971, 0.2236, 0.5086],
        [0.9460, 0.9088, 0.6443]])


In [3]:
meann = tensor.mean()
stdd = tensor.std()
print("\nСреднее значение:", meann.item())
print("Стандартное отклонение:", stdd.item())



Среднее значение: 0.5723546147346497
Стандартное отклонение: 0.31941601634025574


In [5]:
tensor2 = torch.rand(3, 2)
res = torch.matmul(reshape, tensor2)
print(res)

tensor([[0.4684, 0.3846],
        [0.3927, 0.5385],
        [0.1394, 0.2686],
        [0.5909, 0.6233]])


# Упражнение 2: Реализация простой нейронной сети
Цель: Построить и обучить простую искусственную нейронную сеть с использованием PyTorch. 
Инструкции:                                         
	Используйте модуль nn PyTorch для создания сети прямого распространения с одним скрытым слоем.
		Размер входного слоя: 10                       
		Размер скрытого слоя: 5                                      
		Размер выходного слоя: 1                                                    
	Используйте синтетический набор данных (создайте случайные входные данные и соответствующие метки) для обучения вашей модели.                             
	Реализуйте цикл обучения с использованием градиентного спуска для минимизации потерь среднеквадратичной ошибки.                                
	Выведите конечные потери после обучения.                 

In [6]:
import torch
import torch.nn as nn
import torch.optim as optim

X = torch.rand(100, 10) 
y = torch.rand(100, 1)  



In [9]:
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.hidden = nn.Linear(10, 5)  
        self.output = nn.Linear(5, 1)  
        self.activation = nn.ReLU() 

    def forward(self, x):
        x = self.activation(self.hidden(x))
        x = self.output(x)
        return x

model = SimpleNN()

criterion = nn.MSELoss()  # Среднеквадратичная ошибка
optimizer = optim.SGD(model.parameters(), lr=0.01)  

epochs = 10
for epoch in range(epochs):
    predictions = model(X)
    loss = criterion(predictions, y)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    print(f"Эпоха {epoch + 1}, Потери: {loss.item():.4f}")

print("\nКонечные потери", loss.item())


Эпоха 1, Потери: 0.0898
Эпоха 2, Потери: 0.0888
Эпоха 3, Потери: 0.0877
Эпоха 4, Потери: 0.0868
Эпоха 5, Потери: 0.0858
Эпоха 6, Потери: 0.0850
Эпоха 7, Потери: 0.0841
Эпоха 8, Потери: 0.0833
Эпоха 9, Потери: 0.0825
Эпоха 10, Потери: 0.0818

Конечные потери 0.08179454505443573


# Упражнение 3: Визуализация градиентного спуска
Цель: Визуализировать процесс градиентного спуска.
Инструкции:                              
	Создайте простую модель линейной регрессии с использованием PyTorch.                        
	Сгенерируйте синтетические точки данных, которые следуют линейной зависимости с некоторым шумом.
	Обучите свою модель с использованием градиентного спуска и зафиксируйте потери на каждой итерации.
	Постройте график потерь по итерациям, чтобы визуализировать, как они уменьшаются по мере обучения.


In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt


X = torch.linspace(0, 10, 100).view(-1, 1)  
true_slope = 2.0
true_intercept = 1.0
noise = torch.randn(100, 1) * 2.0  
y = true_slope * X + true_intercept + noise

class LinearRegressionModel(nn.Module):
    def __init__(self):
        super(LinearRegressionModel, self).__init__()
        self.linear = nn.Linear(1, 1) 

    def forward(self, x):
        return self.linear(x)

model = LinearRegressionModel()

criterion = nn.MSELoss()  # Среднеквадратичная ошибка
optimizer = optim.SGD(model.parameters(), lr=0.01)  # Градиентный спуск

epochs = 200
losses = []

for epoch in range(epochs):
    predictions = model(X)
    loss = criterion(predictions, y)

    losses.append(loss.item())

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if (epoch + 1) % 50 == 0:
        print(f"Эпоха {epoch + 1}/{epochs}, Потери: {loss.item():.4f}")

plt.figure(figsize=(8, 6))
plt.plot(range(epochs), losses, label='Loss')
plt.xlabel('Итерации')
plt.ylabel('Потери')
plt.title('Снижение потерь в процессе обучения')
plt.legend()
plt.grid(True)
plt.show()


Эпоха 50/200, Потери: 4.6033
Эпоха 100/200, Потери: 4.5696
Эпоха 150/200, Потери: 4.5491
Эпоха 200/200, Потери: 4.5366


# Упражнение 4: Создание CNN для классификации изображений
Цель: Реализовать свёрточную нейронную сеть для классификации изображений.                   
Инструкции:                        
Используйте набор данных CIFAR-10, предоставленный PyTorch.                             
Постройте архитектуру CNN с:                        
Двумя свёрточными слоями, за которыми следуют активация ReLU и подвыборка.                       
Полносвязным слоем для классификации.                        
Обучите вашу CNN на наборе данных CIFAR-10 и оцените её точность на тестовом наборе.         
