# База

1. Созать массив размером 3х3 случ числами от 0 до 10

In [5]:
import numpy as np

a = np.random.randint(0, 10, (3, 3))
print(a)


[[5 9 3]
 [9 7 0]
 [5 5 5]]


2. Найдите сумму и среднее значение элементов массива размером 4х5 запл. случ. целыми числами

In [7]:
b = np.random.randint(0, 11, (4, 5))

summ = np.sum(b)
meann = np.mean(b)

print(b)
print(summ)
print(meann)

[[2 6 1 6 6]
 [3 3 1 3 2]
 [3 6 5 7 6]
 [4 4 1 3 3]]
75
3.75


3. Создайте массив размером 10х1 со знач. от 0 до 9. переобразуете его массив 1х10

In [10]:
c = np.arange(10).reshape(10, 1)

d = arr10x1.reshape(1, 10)

print(d)

[[0 1 2 3 4 5 6 7 8 9]]


4. соз. массив из всех нечетных числ от 10 до 30

In [11]:
e = np.arange(11, 30, 2)

print(e)

[11 13 15 17 19 21 23 25 27 29]


5. замените все знач. в массиве 5х5, кроме его границ, на нули

In [12]:
f = np.random.randint(1, 10, (5, 5))

f[1:-1, 1:-1] = 0

print(f)

[[1 6 4 9 4]
 [5 0 0 0 1]
 [4 0 0 0 8]
 [8 0 0 0 8]
 [6 6 8 5 5]]


6. создайте массив длинной 10, запл единицами,и замените значения с третьего по пятое на 0

In [14]:
g = np.ones(10)

g[2:5] = 0

print(g)

[1. 1. 0. 0. 0. 1. 1. 1. 1. 1.]


# Сред

7. соз. 2д массив с разм 6х6 и заполните его диоганадьные элем значениями 1

In [15]:
h = np.zeros((6, 6))

np.fill_diagonal(h, 1)

print(h)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


8. соз. массив с размером 5х5, запл. случ. числами от 1 до 100, и найдите позиции всех знач. превышающих 50

In [18]:
i = np.random.randint(0, 100, (5, 5))
pos= np.argwhere(i > 50)

print(i)
print(pos)

[[15 71 62  7 12]
 [12 92 47 22 34]
 [ 8 90 49 75 72]
 [ 9 66 38 65 90]
 [70 13 36 58 17]]
[[0 1]
 [0 2]
 [1 1]
 [2 1]
 [2 3]
 [2 4]
 [3 1]
 [3 3]
 [3 4]
 [4 0]
 [4 3]]


9. соз. массив 7х7 и замените все элем, кратные 3, на число -1

In [19]:
import numpy as np

j= np.random.randint(1, 101, (7, 7))

j[j % 3 == 0] = -1

print(j)

[[70 98 -1 10 -1 23 -1]
 [16 31 28 -1 28 53  8]
 [92 89 -1 61 40 10 86]
 [23 70 91 64 -1 77 82]
 [22 16 86 73  7 82 -1]
 [79 91 55 -1 -1 -1 94]
 [-1 10 -1 -1 76 -1 -1]]


10. соз. массив и найдите суммы всех его четных элем.

In [27]:
k = np.random.randint(1, 101, (10, 10))
s= np.sum(k[k % 2 == 0])

print(k)
print(s)


[[86 92 57 85  5 94 17  9 34 95]
 [97  3 70 83 40 91 25 79 67 96]
 [26 25 39 66 45 99 81 40 99 12]
 [66 96 19 28 70 58  1 29 38 38]
 [43 56 11 42 16 74 90 37 34 48]
 [78 71 80 55 96 94 70 78 56  8]
 [16 46 23 25 95 23 15 25 72 26]
 [58 54  5 55 80 14 81 59 21  9]
 [97 87 77 93  1 83 94 37 50 66]
 [41 67 42 15 52 27 29  5 44 49]]
2684


11. найдите индексы максим знач. в каждом столбце массива с разм 4х4

In [28]:
l = np.random.randint(1, 101, (4, 4))
m= np.argmax(l, axis=0) # в каком напр выпл. опер.

print(l)
print(m)


[[81 31 13 33]
 [86 33 39 66]
 [55 28 64  9]
 [97 78 35  7]]
[3 3 2 1]


12. создайте 2д массив и замените в нем все элем, находящися в верхней трети по значению, на их отрицательное значения

In [32]:
o = np.random.randint(0, 100, (4, 4))

o


array([[23,  8, 35, 75],
       [33, 93, 78, 55],
       [94, 93, 31, 43],
       [43,  9, 85, 48]])